name: Blog
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: nightly i choose u
        run: rustup default nightly
      - name: now trunk
        run: cargo install trunk
      - name: now wasm
        run: rustup target add wasm32-unknown-unknown
      - name: now build
        run: trunk build
      - name: deploy
        run: vercel deploy --prebuilt --prod --token=wbX9rrhJd4P2kFnRFt4oDmHB
